# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Unit tests

on: 
  push:
    branches: [main]

jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install flake8 pytest
        pip3 install -r requirements.txt
        pip3 install -e .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with PyTest
      run: |
        python -m pytest --cov-report=xml
    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v3.1.0
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     directory: ./coverage/reports/
    #     env_vars: OS,PYTHON
    #     fail_ci_if_error: true
    #     flags: unittests
    #     name: codecov-umbrella
    #     path_to_write_report: ./coverage/codecov_report.txt
    #     verbose: true
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      # with:
      #   token: ${{ secrets.CODECOV_TOKEN }}
        # flags: unittests
    # - name: Upload coverage to Codecov
    #   run: |
    #     # Replace `linux` below with the appropriate OS
    #     # Options are `alpine`, `linux`, `macos`, `windows`
    #     curl -Os https://uploader.codecov.io/latest/macos/codecov
    #     chmod +x codecov
    #     ./codecov -t ${CODECOV_TOKEN}